#!/usr/bin/env python3
"""Azure OpenAI agent that writes variant-interpretation memos.

Two modes:

  * DEFAULT -- cohort memo. The whole VCF is annotated in ONE batch pass
    (src/annotate.py: batched MyVariant.info + Ensembl VEP POSTs) and classified
    by the simplified ACMG engine (src/acmg.py). The annotated + classified JSON,
    plus a precomputed deterministic ``summary`` (counts, allele-frequency
    profile, notable calls), is handed to the model, which writes a single cohort
    memo -- overview, statistics, notable variants, patterns/caveats -- grounded
    in those numbers.
  * --per-variant -- legacy tool-calling loop. For each variant the model calls
    two tools (``annotate_variant`` -> src/annotate.py, ``classify_variant`` ->
    src/acmg.py), then writes one memo per variant.

Every memo CITES its data sources (MyVariant.info / ClinVar / gnomAD / Ensembl
VEP) and ends with the mandatory research-only disclaimer.

Auth: API key (AZURE_OPENAI_API_KEY) OR keyless AAD (AZURE_OPENAI_USE_AAD=true)
via azure-identity DefaultAzureCredential.

RESEARCH / EDUCATION ONLY -- not for clinical use.
"""
from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any

# Local lab modules.
sys.path.insert(0, str(Path(__file__).resolve().parent))
import acmg  # noqa: E402
import annotate as annotate_mod  # noqa: E402

try:
    from dotenv import load_dotenv

    # Load .env from the scenario root (parent of src/) regardless of cwd,
    # then honor any ambient .env / real environment variables too.
    load_dotenv(Path(__file__).resolve().parents[1] / ".env")
    load_dotenv()
except Exception:  # pragma: no cover
    pass

# Make stdout/stderr UTF-8 so memos with gene symbols / arrows print on Windows.
for _stream in (sys.stdout, sys.stderr):
    try:
        _stream.reconfigure(encoding="utf-8")  # type: ignore[attr-defined]
    except Exception:  # pragma: no cover - older Pythons / redirected streams
        pass

# --- Azure OpenAI configuration (read once) -------------------------------- #
ENDPOINT = os.getenv("AZURE_OPENAI_ENDPOINT", "")
API_KEY = os.getenv("AZURE_OPENAI_API_KEY", "")
DEPLOYMENT = os.getenv("AZURE_OPENAI_DEPLOYMENT", "gpt-5.1")
API_VERSION = os.getenv("AZURE_OPENAI_API_VERSION", "2024-10-21")

DISCLAIMER = (
    "> **DISCLAIMER -- RESEARCH / EDUCATION ONLY. NOT FOR CLINICAL USE.** "
    "This memo was generated by an automated teaching pipeline using a "
    "simplified ACMG/AMP heuristic subset and must not be used to diagnose, "
    "treat, or make any medical decision. Clinical interpretation requires a "
    "qualified molecular geneticist in an accredited (CAP/CLIA) laboratory."
)

SYSTEM_PROMPT = (
    "You are a careful genomics teaching assistant. For the given variant, you "
    "MUST call the annotate_variant tool (pass the dbSNP rsID when one is given), "
    "then the classify_variant tool, and only then write a concise markdown "
    "interpretation memo. The memo MUST: "
    "(1) state the variant, gene, ClinVar significance, and gnomAD allele "
    "frequency; (2) list each ACMG criterion that fired with its rationale and "
    "the final classification; (3) include a 'Data sources' section citing "
    "MyVariant.info (ClinVar, gnomAD) and Ensembl VEP as applicable; (4) end "
    "with the exact disclaimer provided to you. Never overstate certainty. "
    "Make clear this is a simplified educational classification."
)

# Five-tier ACMG order for a stable classification breakdown in the summary.
CLASS_ORDER = [
    "Pathogenic",
    "Likely pathogenic",
    "Uncertain significance (VUS)",
    "Likely benign",
    "Benign",
]

# Cap how many per-variant records are inlined into the cohort prompt. The
# deterministic summary always covers ALL variants, so large cohorts stay
# grounded even when the record list is truncated for token budget.
MAX_RECORDS_IN_PROMPT = int(os.getenv("AGENT_MAX_RECORDS_IN_PROMPT", "300"))
AGENT_CHUNK_RECORDS = int(os.getenv("AGENT_CHUNK_RECORDS", "250"))
PATHOGENIC_AND_VUS_CLASSES = {
    "Pathogenic",
    "Likely pathogenic",
    "Uncertain significance (VUS)",
}

COHORT_SYSTEM_PROMPT = (
    "You are a careful genomics teaching assistant writing a COHORT-level "
    "variant-interpretation memo. You are given a JSON payload with (a) a "
    "precomputed deterministic `summary` (counts and statistics over the whole "
    "cohort) and (b) per-variant `records`, each ALREADY annotated "
    "(MyVariant.info: ClinVar, gnomAD, dbNSFP; Ensembl VEP) and classified by a "
    "simplified ACMG/AMP engine. Do NOT re-annotate or re-classify, and base "
    "every number on the provided `summary`/`records` -- never invent figures "
    "(the `summary` covers all variants even if `records` is truncated). Write a "
    "structured markdown memo with: (1) a one-paragraph overview (cohort size, "
    "headline finding); (2) '## Cohort statistics' from the summary "
    "(classification breakdown, ClinVar spread, allele-frequency profile, "
    "most-severe consequences); (3) '## Notable variants' highlighting the "
    "Pathogenic / Likely pathogenic calls and any interesting tensions (e.g. "
    "ClinVar Pathogenic yet common in gnomAD -> tempered toward benign); "
    "(4) '## Patterns & caveats' surfacing anything scientifically interesting "
    "(VUS burden, unannotated variants, allele-frequency outliers, in-silico "
    "disagreements); (5) '## Data sources' citing MyVariant.info (ClinVar, "
    "gnomAD) and Ensembl VEP; (6) end with the EXACT disclaimer provided. Never "
    "overstate certainty; make clear this is a simplified educational "
    "classification, not a clinical report."
)


# --------------------------------------------------------------------------- #
# Azure OpenAI client
# --------------------------------------------------------------------------- #
def build_client():
    """Construct the AzureOpenAI client (keyless Entra ID by default).

    Auth: if AZURE_OPENAI_API_KEY is set we use key auth; otherwise we fall back
    to keyless Microsoft Entra ID auth (DefaultAzureCredential -- your `az login`
    session locally, or a managed identity on Azure). An *empty* key value is
    treated as absent, so keyless still works when the key line is blank.

    Two endpoint styles are auto-selected:
      * classic data plane -> https://<res>.openai.azure.com/  (azure_endpoint)
      * OpenAI v1 surface   -> https://<res>.services.ai.azure.com/openai/v1/
        (base_url) -- required by the newest deployments.
    Imported lazily so the module still imports cleanly in CI (no SDK/creds).
    """
    from openai import AzureOpenAI

    if not ENDPOINT:
        raise RuntimeError(
            "Azure OpenAI endpoint missing. Copy .env.example to .env and set "
            "AZURE_OPENAI_ENDPOINT (and AZURE_OPENAI_DEPLOYMENT)."
        )

    _endpoint = ENDPOINT.rstrip("/")
    if _endpoint.endswith("/openai/v1"):
        route_kwargs: dict[str, Any] = {"base_url": _endpoint + "/"}
    else:
        route_kwargs = {"azure_endpoint": _endpoint}

    if API_KEY:
        return AzureOpenAI(api_key=API_KEY, api_version=API_VERSION, **route_kwargs)

    # Keyless / Entra ID auth (no API key required).
    try:
        from azure.identity import DefaultAzureCredential, get_bearer_token_provider
    except ModuleNotFoundError:
        # Fallback for environments where azure-identity/cryptography wheels are
        # unavailable: use an Azure CLI token from an existing `az login` session.
        az_exe = shutil.which("az")
        if not az_exe and os.name == "nt":
            az_exe = shutil.which("az.cmd")
        if not az_exe and os.name == "nt":
            for candidate in (
                r"C:\Program Files\Microsoft SDKs\Azure\CLI2\wbin\az.cmd",
                r"C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd",
            ):
                if os.path.exists(candidate):
                    az_exe = candidate
                    break
        try:
            cli = subprocess.run(
                [
                    az_exe or "az",
                    "account",
                    "get-access-token",
                    "--resource",
                    "https://cognitiveservices.azure.com/",
                    "--output",
                    "json",
                ],
                check=True,
                capture_output=True,
                text=True,
            )
        except FileNotFoundError as exc:
            raise RuntimeError(
                "Keyless auth requested but azure-identity is unavailable and "
                "`az` was not found. Install Azure CLI and run `az login`, or set "
                "AZURE_OPENAI_API_KEY for key auth."
            ) from exc
        except subprocess.CalledProcessError as exc:
            detail = (exc.stderr or exc.stdout or "").strip()
            raise RuntimeError(
                "Failed to acquire Azure token via Azure CLI. Run `az login` and "
                "ensure your account has access to this Azure OpenAI resource."
                + (f" Details: {detail}" if detail else "")
            ) from exc

        payload = json.loads(cli.stdout)
        token = payload.get("accessToken")
        if not token:
            raise RuntimeError(
                "Azure CLI returned no accessToken. Re-run `az login` and retry."
            )
        return AzureOpenAI(
            azure_ad_token=token,
            api_version=API_VERSION,
            **route_kwargs,
        )

    token_provider = get_bearer_token_provider(
        DefaultAzureCredential(),
        "https://cognitiveservices.azure.com/.default",
    )
    return AzureOpenAI(
        azure_ad_token_provider=token_provider,
        api_version=API_VERSION,
        **route_kwargs,
    )


# --------------------------------------------------------------------------- #
# Tool implementations (called locally when the model requests them)
# --------------------------------------------------------------------------- #
def _tool_annotate(
    chrom: str, pos: int, ref: str, alt: str, rsid: str = "."
) -> dict[str, Any]:
    variant = annotate_mod.Variant(
        chrom=chrom, pos=int(pos), ref=ref, alt=alt, rsid=rsid
    )
    return annotate_mod.annotate_variant(variant)


def _tool_classify(annotation: dict[str, Any]) -> dict[str, Any]:
    return acmg.evaluate(annotation).to_dict()


TOOLS = [
    {
        "type": "function",
        "function": {
            "name": "annotate_variant",
            "description": (
                "Annotate a single genomic variant against MyVariant.info "
                "(ClinVar significance, gnomAD allele frequency, dbNSFP scores) "
                "and Ensembl VEP (most-severe consequence)."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "chrom": {"type": "string", "description": "Chromosome, e.g. 17 or chr17"},
                    "pos": {"type": "integer", "description": "1-based genomic position"},
                    "ref": {"type": "string", "description": "Reference allele"},
                    "alt": {"type": "string", "description": "Alternate allele"},
                    "rsid": {
                        "type": "string",
                        "description": "dbSNP rsID from the VCF ID column (e.g. rs334) when available; enables reliable ClinVar/gnomAD lookup, including for indels.",
                    },
                },
                "required": ["chrom", "pos", "ref", "alt"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "classify_variant",
            "description": (
                "Run the simplified ACMG/AMP rule engine on an annotation dict "
                "previously returned by annotate_variant. Returns fired criteria "
                "and a classification."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "annotation": {
                        "type": "object",
                        "description": "The dict returned by annotate_variant.",
                    }
                },
                "required": ["annotation"],
            },
        },
    },
]

TOOL_IMPLS = {
    "annotate_variant": lambda args: _tool_annotate(**args),
    "classify_variant": lambda args: _tool_classify(args["annotation"]),
}


# --------------------------------------------------------------------------- #
# Agent loop
# --------------------------------------------------------------------------- #
def interpret_variant(client, deployment: str, variant: annotate_mod.Variant) -> str:
    """Run the tool-calling loop for one variant and return the memo markdown."""
    user_msg = (
        "Interpret this variant and write the memo.\n"
        f"chrom={variant.chrom} pos={variant.pos} ref={variant.ref} "
        f"alt={variant.alt} (id={variant.rsid}).\n"
        f"End the memo with EXACTLY this disclaimer line:\n{DISCLAIMER}"
    )
    messages: list[dict[str, Any]] = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": user_msg},
    ]

    # gpt-5 / o-series reasoning models only allow the default sampling
    # temperature (1); sending temperature=0.2 returns a 400. Only pass it for
    # models that accept a custom value.
    supports_temperature = not any(
        tag in deployment.lower() for tag in ("gpt-5", "o1", "o3", "o4")
    )

    # Bounded loop: the model may call annotate, then classify, then answer.
    for _ in range(6):
        create_kwargs: dict[str, Any] = {
            "model": deployment,
            "messages": messages,
            "tools": TOOLS,
            "tool_choice": "auto",
        }
        if supports_temperature:
            create_kwargs["temperature"] = 0.2
        resp = client.chat.completions.create(**create_kwargs)
        msg = resp.choices[0].message
        messages.append(msg.model_dump(exclude_none=True))

        if not msg.tool_calls:
            content = msg.content or ""
            # Defensive: guarantee the disclaimer is present.
            if "NOT FOR CLINICAL USE" not in content.upper():
                content = content.rstrip() + "\n\n" + DISCLAIMER
            return content

        for call in msg.tool_calls:
            name = call.function.name
            try:
                args = json.loads(call.function.arguments or "{}")
                result = TOOL_IMPLS[name](args)
            except Exception as exc:  # surface tool errors back to the model
                result = {"error": f"{type(exc).__name__}: {exc}"}
            messages.append(
                {
                    "role": "tool",
                    "tool_call_id": call.id,
                    "name": name,
                    "content": json.dumps(result, default=str),
                }
            )

    return "Agent did not converge within the tool-call budget.\n\n" + DISCLAIMER


# --------------------------------------------------------------------------- #
# Cohort mode (default): batch-annotate the whole VCF, then write ONE memo
# --------------------------------------------------------------------------- #
def annotate_and_classify(
    path: str, assembly: str = annotate_mod.ASSEMBLY, limit: int = 0
) -> list[dict[str, Any]]:
    """Batch-annotate a whole VCF, then attach a simplified ACMG classification.

    Uses the batched annotate path (a few POSTs for the entire file) plus the
    deterministic ACMG engine -- NO model calls. Each returned record is the
    annotation dict with an added ``classification`` key.
    """
    records = annotate_mod.annotate_vcf(path, assembly=assembly, limit=limit)
    for rec in records:
        rec["classification"] = acmg.evaluate(rec).to_dict()
    return records


def _cohort_summary(records: list[dict[str, Any]]) -> dict[str, Any]:
    """Deterministic counts/statistics over the cohort (grounds the memo).

    Computed in Python -- not by the model -- so every figure in the memo traces
    to a real count rather than an LLM guess over a long list.
    """
    from collections import Counter
    from statistics import median

    class_counts: Counter[str] = Counter()
    clinvar_counts: Counter[str] = Counter()
    consequence_counts: Counter[str] = Counter()
    afs: list[float] = []
    unannotated = 0
    notable: list[dict[str, Any]] = []

    for rec in records:
        cls = (rec.get("classification") or {}).get("classification", "Unknown")
        class_counts[cls] += 1
        if not rec.get("found"):
            unannotated += 1
        clinvar_counts[str(rec.get("clinvar_significance") or "not provided")] += 1
        cons = rec.get("most_severe_consequence")
        if cons:
            consequence_counts[cons] += 1
        af = rec.get("gnomad_af")
        if isinstance(af, (int, float)):
            afs.append(float(af))
        if cls in ("Pathogenic", "Likely pathogenic"):
            var = rec.get("variant", {})
            notable.append(
                {
                    "hgvs_id": rec.get("hgvs_id"),
                    "gene": rec.get("gene") or var.get("info", {}).get("GENE"),
                    "rsid": var.get("rsid"),
                    "classification": cls,
                    "clinvar_significance": rec.get("clinvar_significance"),
                    "gnomad_af": af,
                    "most_severe_consequence": rec.get("most_severe_consequence"),
                    "criteria": [
                        c.get("code")
                        for c in (rec.get("classification") or {}).get("criteria", [])
                    ],
                }
            )

    classification_counts: dict[str, int] = {}
    for k in CLASS_ORDER:
        if class_counts.get(k):
            classification_counts[k] = class_counts[k]
    for k, v in class_counts.items():
        classification_counts.setdefault(k, v)

    af_profile = {
        "variants_with_af": len(afs),
        "rare_lt_1e-4": sum(1 for a in afs if a < 1e-4),
        "common_gt_5pct": sum(1 for a in afs if a > 0.05),
        "min": min(afs) if afs else None,
        "median": median(afs) if afs else None,
        "max": max(afs) if afs else None,
    }

    return {
        "total_variants": len(records),
        "unannotated": unannotated,
        "classification_counts": classification_counts,
        "clinvar_significance_counts": dict(clinvar_counts.most_common()),
        "most_severe_consequence_counts": dict(consequence_counts.most_common()),
        "allele_frequency_profile": af_profile,
        "notable_variant_count": len(notable),
        "notable_variants": notable[:50],
    }


def _write_classification_distribution_graph(
    summary: dict[str, Any], output_path: Path
) -> None:
    """Write a bar chart for classification distribution, if matplotlib exists."""
    try:
        import matplotlib.pyplot as plt
    except ModuleNotFoundError:
        print(
            "[WARN] matplotlib is not installed; skipping distribution graph.",
            file=sys.stderr,
        )
        return

    counts = summary.get("classification_counts", {})
    labels = [name for name in CLASS_ORDER if counts.get(name)]
    if not labels:
        print("[WARN] No classifications available for graph output.", file=sys.stderr)
        return

    values = [int(counts[name]) for name in labels]
    colors = {
        "Pathogenic": "#d62728",
        "Likely pathogenic": "#ff7f0e",
        "Uncertain significance (VUS)": "#ffdd57",
        "Likely benign": "#98df8a",
        "Benign": "#2ca02c",
    }
    bar_colors = [colors.get(label, "#1f77b4") for label in labels]

    fig, ax = plt.subplots(figsize=(11, 6))
    bars = ax.bar(labels, values, color=bar_colors, edgecolor="black", linewidth=1.0)
    ax.set_title("Variant Classification Distribution", fontsize=14, fontweight="bold")
    ax.set_ylabel("Count", fontsize=12)
    ax.tick_params(axis="x", rotation=20)
    ax.grid(axis="y", linestyle="--", alpha=0.3)
    for bar, value in zip(bars, values, strict=False):
        ax.text(
            bar.get_x() + bar.get_width() / 2,
            value,
            str(value),
            ha="center",
            va="bottom",
            fontweight="bold",
        )
    fig.tight_layout()
    fig.savefig(output_path, dpi=300, bbox_inches="tight")
    plt.close(fig)


def _classification_name(record: dict[str, Any]) -> str:
    return str((record.get("classification") or {}).get("classification") or "")


def _slim_record(rec: dict[str, Any]) -> dict[str, Any]:
    """Trim an annotated + classified record to the memo-relevant fields."""
    var = rec.get("variant", {})
    cls = rec.get("classification") or {}
    return {
        "hgvs_id": rec.get("hgvs_id"),
        "gene": rec.get("gene") or var.get("info", {}).get("GENE"),
        "rsid": var.get("rsid"),
        "found": rec.get("found", False),
        "clinvar_significance": rec.get("clinvar_significance"),
        "clinvar_review_status": rec.get("clinvar_review_status"),
        "gnomad_af": rec.get("gnomad_af"),
        "most_severe_consequence": rec.get("most_severe_consequence"),
        "sift_pred": rec.get("sift_pred"),
        "polyphen_pred": rec.get("polyphen_pred"),
        "cadd_phred": rec.get("cadd_phred"),
        "classification": cls.get("classification"),
        "criteria": [c.get("code") for c in cls.get("criteria", [])],
    }


def _supports_temperature(deployment: str) -> bool:
    return not any(tag in deployment.lower() for tag in ("gpt-5", "o1", "o3", "o4"))


def _json_from_text(text: str) -> dict[str, Any] | None:
    stripped = text.strip()
    if stripped.startswith("```"):
        lines = stripped.splitlines()
        if lines and lines[0].startswith("```"):
            lines = lines[1:]
        if lines and lines[-1].startswith("```"):
            lines = lines[:-1]
        stripped = "\n".join(lines).strip()
    start = stripped.find("{")
    end = stripped.rfind("}")
    if start == -1 or end == -1 or end <= start:
        return None
    try:
        parsed = json.loads(stripped[start : end + 1])
    except (TypeError, ValueError):
        return None
    return parsed if isinstance(parsed, dict) else None


def _chunk_records(records: list[dict[str, Any]], chunk_size: int) -> list[list[dict[str, Any]]]:
    return [records[i : i + chunk_size] for i in range(0, len(records), chunk_size)]


def _analyze_chunk_for_memo(
    client,
    deployment: str,
    chunk: list[dict[str, Any]],
    chunk_index: int,
    chunk_count: int,
    global_summary: dict[str, Any],
) -> dict[str, Any]:
    chunk_summary = _cohort_summary(chunk)
    payload = {
        "chunk_index": chunk_index,
        "chunk_count": chunk_count,
        "chunk_summary": chunk_summary,
        "records": [_slim_record(r) for r in chunk],
        "global_summary": global_summary,
    }
    user_msg = (
        "Analyze this ONE chunk of precomputed Pathogenic/Likely pathogenic/VUS "
        "records and return STRICT JSON only (no markdown, no prose outside JSON) "
        "with exactly these keys: chunk_index, variants_in_chunk, key_signals, "
        "notable_variants, caveats. Keep it concise: key_signals <= 8 strings, "
        "notable_variants <= 12 objects "
        "(hgvs_id,gene,classification,why_notable), caveats <= 6 strings.\n\n"
        f"```json\n{json.dumps(payload, default=str, indent=2)}\n```"
    )
    messages: list[dict[str, Any]] = [
        {"role": "system", "content": COHORT_SYSTEM_PROMPT},
        {"role": "user", "content": user_msg},
    ]
    create_kwargs: dict[str, Any] = {"model": deployment, "messages": messages}
    if _supports_temperature(deployment):
        create_kwargs["temperature"] = 0.2
    resp = client.chat.completions.create(**create_kwargs)
    content = resp.choices[0].message.content or ""
    parsed = _json_from_text(content) or {}
    key_signals = parsed.get("key_signals")
    notable = parsed.get("notable_variants")
    caveats = parsed.get("caveats")
    return {
        "chunk_index": chunk_index,
        "variants_in_chunk": len(chunk),
        "key_signals": key_signals[:8] if isinstance(key_signals, list) else [],
        "notable_variants": notable[:12] if isinstance(notable, list) else [],
        "caveats": caveats[:6] if isinstance(caveats, list) else [],
    }


def _write_cohort_memo_single_pass(
    client,
    deployment: str,
    records: list[dict[str, Any]],
    summary: dict[str, Any],
) -> str:
    """Ask the model to write ONE cohort memo from precomputed annotations+stats."""
    if len(records) > MAX_RECORDS_IN_PROMPT:
        # Prioritize the clinically interesting calls, then fill to the cap.
        priority: list[dict[str, Any]] = []
        rest: list[dict[str, Any]] = []
        for r in records:
            cls = (r.get("classification") or {}).get("classification")
            bucket = priority if cls in (
                "Pathogenic",
                "Likely pathogenic",
                "Uncertain significance (VUS)",
            ) else rest
            bucket.append(r)
        shown = (priority + rest)[:MAX_RECORDS_IN_PROMPT]
        truncated = True
    else:
        shown = records
        truncated = False

    payload = {
        "summary": summary,
        "records": [_slim_record(r) for r in shown],
        "records_shown": len(shown),
        "records_total": len(records),
        "records_truncated": truncated,
    }
    user_msg = (
        "Write the cohort interpretation memo from this precomputed JSON "
        "(already annotated + classified -- do not recompute the numbers). The "
        "`summary` covers ALL variants even when `records` is truncated for "
        "size.\n\n"
        f"```json\n{json.dumps(payload, default=str, indent=2)}\n```\n\n"
        f"End the memo with EXACTLY this disclaimer line:\n{DISCLAIMER}"
    )
    messages: list[dict[str, Any]] = [
        {"role": "system", "content": COHORT_SYSTEM_PROMPT},
        {"role": "user", "content": user_msg},
    ]
    create_kwargs: dict[str, Any] = {"model": deployment, "messages": messages}
    if _supports_temperature(deployment):
        create_kwargs["temperature"] = 0.2
    resp = client.chat.completions.create(**create_kwargs)
    content = resp.choices[0].message.content or ""
    if "NOT FOR CLINICAL USE" not in content.upper():
        content = content.rstrip() + "\n\n" + DISCLAIMER
    return content


def write_cohort_memo(
    client,
    deployment: str,
    records: list[dict[str, Any]],
    summary: dict[str, Any],
) -> tuple[str, list[dict[str, Any]], str]:
    """Write cohort memo with adaptive strategy based on input size.

    Returns (memo_text, chunk_analyses, strategy_used).
    """
    if len(records) <= MAX_RECORDS_IN_PROMPT:
        return _write_cohort_memo_single_pass(
            client, deployment, records, summary
        ), [], "single_pass"

    chunk_size = max(1, AGENT_CHUNK_RECORDS)
    chunks = _chunk_records(records, chunk_size)
    print(
        f"  [INFO] Using adaptive map-reduce memo generation for {len(records)} "
        f"records ({len(chunks)} chunks of up to {chunk_size}).",
        file=sys.stderr,
    )
    chunk_analyses: list[dict[str, Any]] = []
    for i, chunk in enumerate(chunks, start=1):
        print(f"    - analyzing chunk {i}/{len(chunks)}", file=sys.stderr)
        chunk_analyses.append(
            _analyze_chunk_for_memo(
                client=client,
                deployment=deployment,
                chunk=chunk,
                chunk_index=i,
                chunk_count=len(chunks),
                global_summary=summary,
            )
        )

    synth_payload = {
        "summary": summary,
        "records_total": len(records),
        "chunk_count": len(chunks),
        "chunk_analyses": chunk_analyses,
    }
    user_msg = (
        "Write a comprehensive cohort memo using ALL chunk analyses and the global "
        "summary. Every numeric cohort claim must come from `summary`; use chunk "
        "analyses for detailed evidence patterns and notable examples. "
        "Do not invent counts.\n\n"
        f"```json\n{json.dumps(synth_payload, default=str, indent=2)}\n```\n\n"
        f"End the memo with EXACTLY this disclaimer line:\n{DISCLAIMER}"
    )
    messages: list[dict[str, Any]] = [
        {"role": "system", "content": COHORT_SYSTEM_PROMPT},
        {"role": "user", "content": user_msg},
    ]
    create_kwargs: dict[str, Any] = {"model": deployment, "messages": messages}
    if _supports_temperature(deployment):
        create_kwargs["temperature"] = 0.2
    resp = client.chat.completions.create(**create_kwargs)
    memo = resp.choices[0].message.content or ""
    if "NOT FOR CLINICAL USE" not in memo.upper():
        memo = memo.rstrip() + "\n\n" + DISCLAIMER
    return memo, chunk_analyses, "map_reduce"


def _slug(variant: annotate_mod.Variant) -> str:
    return f"{variant.chrom}_{variant.pos}_{variant.ref}_{variant.alt}".replace(
        "chr", ""
    )


def _main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("vcf", help="path to a VCF file")
    ap.add_argument(
        "--out-dir", default="output/memos", help="directory for the .md memos"
    )
    ap.add_argument(
        "--limit",
        type=int,
        default=0,
        help="only process first N variants in --per-variant mode",
    )
    ap.add_argument(
        "--assembly",
        default=annotate_mod.ASSEMBLY,
        help="genome build for annotation (hg19 or hg38)",
    )
    ap.add_argument(
        "--per-variant",
        action="store_true",
        help="legacy mode: one tool-calling memo PER variant (no batch, no cohort)",
    )
    args = ap.parse_args(argv)

    deployment = DEPLOYMENT
    client = build_client()
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    # Legacy per-variant tool-calling mode: the model annotates each variant
    # itself (single lookups) and writes one memo per variant.
    if args.per_variant:
        variants = annotate_mod.parse_vcf(args.vcf)
        if args.limit:
            variants = variants[: args.limit]
        for v in variants:
            print(f"Interpreting {v.hgvs_id} ...", file=sys.stderr)
            memo = interpret_variant(client, deployment, v)
            path = out_dir / f"memo_{_slug(v)}.md"
            path.write_text(memo, encoding="utf-8")
            print(f"  -> {path}")
        return 0

    # Default: batch-annotate + classify the whole VCF (no model calls), then
    # hand the annotated JSON + deterministic stats to the model for ONE memo.
    if args.limit:
        print(
            "[INFO] --limit is ignored in cohort batch mode; processing ALL variants.",
            file=sys.stderr,
        )
    print("Batch-annotating + classifying the cohort ...", file=sys.stderr)
    records = annotate_and_classify(args.vcf, assembly=args.assembly, limit=0)
    if not records:
        print("No variants found in the VCF.", file=sys.stderr)
        return 1
    summary = _cohort_summary(records)
    vcf_stem = Path(args.vcf).stem
    full_json_path = out_dir / "cohort_annotations.json"
    full_json_path.write_text(json.dumps(records, default=str, indent=2), encoding="utf-8")

    graph_path = out_dir / f"{vcf_stem}_classification_distribution.png"
    _write_classification_distribution_graph(summary, graph_path)

    path_and_vus_records = [
        rec
        for rec in records
        if _classification_name(rec) in PATHOGENIC_AND_VUS_CLASSES
    ]
    path_and_vus_path = out_dir / f"{vcf_stem}_PathAndVUS.json"
    path_and_vus_path.write_text(
        json.dumps(path_and_vus_records, default=str, indent=2),
        encoding="utf-8",
    )

    memo_summary = _cohort_summary(path_and_vus_records)
    print(
        f"  {summary['total_variants']} variants; "
        f"{memo_summary['total_variants']} Pathogenic/Likely pathogenic/VUS. "
        "Writing memo on filtered subset ...",
        file=sys.stderr,
    )
    memo, chunk_analyses, strategy = write_cohort_memo(
        client, deployment, path_and_vus_records, memo_summary
    )
    memo_path = out_dir / "cohort_memo.md"
    memo_path.write_text(memo, encoding="utf-8")
    chunk_analysis_path = out_dir / f"{vcf_stem}_PathAndVUS_chunk_analyses.json"
    if chunk_analyses:
        chunk_analysis_path.write_text(
            json.dumps(chunk_analyses, default=str, indent=2),
            encoding="utf-8",
        )
    print(f"  -> {memo_path}")
    print(f"  -> {full_json_path}  (all annotated + classified variants)")
    print(f"  -> {path_and_vus_path}  (Pathogenic/Likely pathogenic/VUS only)")
    print(f"  -> {graph_path}  (classification distribution graph)")
    if chunk_analyses:
        print(
            f"  -> {chunk_analysis_path}  (intermediate chunk analyses for "
            f"{strategy} memo synthesis)"
        )
    return 0


if __name__ == "__main__":
    sys.exit(_main())
