#!/usr/bin/env python3
"""Azure OpenAI tool-calling agent that writes variant-interpretation memos.

The agent is given two tools:

  * ``annotate_variant`` -> wraps src/annotate.py (MyVariant.info + VEP)
  * ``classify_variant`` -> wraps src/acmg.py (simplified ACMG rule engine)

For each variant in the input VCF the agent runs a tool-calling loop, then is
asked to produce a structured markdown memo that:

  * summarizes the variant, gene, ClinVar significance, and gnomAD frequency,
  * lists the ACMG criteria that fired and the resulting classification,
  * CITES the data sources (MyVariant.info / ClinVar / gnomAD / Ensembl VEP),
  * ends with the mandatory research-only disclaimer.

Auth: API key (AZURE_OPENAI_API_KEY) OR keyless AAD (AZURE_OPENAI_USE_AAD=true)
via azure-identity DefaultAzureCredential.

RESEARCH / EDUCATION ONLY -- not for clinical use.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Any

# Local lab modules.
sys.path.insert(0, str(Path(__file__).resolve().parent))
import acmg  # noqa: E402
import annotate as annotate_mod  # noqa: E402

try:
    from dotenv import load_dotenv

    load_dotenv()
except Exception:  # pragma: no cover
    pass

DISCLAIMER = (
    "> **DISCLAIMER -- RESEARCH / EDUCATION ONLY. NOT FOR CLINICAL USE.** "
    "This memo was generated by an automated teaching pipeline using a "
    "simplified ACMG/AMP heuristic subset and must not be used to diagnose, "
    "treat, or make any medical decision. Clinical interpretation requires a "
    "qualified molecular geneticist in an accredited (CAP/CLIA) laboratory."
)

SYSTEM_PROMPT = (
    "You are a careful genomics teaching assistant. For the given variant, you "
    "MUST call the annotate_variant tool, then the classify_variant tool, and "
    "only then write a concise markdown interpretation memo. The memo MUST: "
    "(1) state the variant, gene, ClinVar significance, and gnomAD allele "
    "frequency; (2) list each ACMG criterion that fired with its rationale and "
    "the final classification; (3) include a 'Data sources' section citing "
    "MyVariant.info (ClinVar, gnomAD) and Ensembl VEP as applicable; (4) end "
    "with the exact disclaimer provided to you. Never overstate certainty. "
    "Make clear this is a simplified educational classification."
)


# --------------------------------------------------------------------------- #
# Azure OpenAI client
# --------------------------------------------------------------------------- #
def build_client():
    """Create an AzureOpenAI client (API key or AAD)."""
    from openai import AzureOpenAI

    endpoint = os.environ["AZURE_OPENAI_ENDPOINT"]
    api_version = os.getenv("AZURE_OPENAI_API_VERSION", "2024-10-21")

    if os.getenv("AZURE_OPENAI_USE_AAD", "false").lower() == "true":
        # Keyless auth via azure-identity (no secret in .env).
        from azure.identity import DefaultAzureCredential, get_bearer_token_provider

        token_provider = get_bearer_token_provider(
            DefaultAzureCredential(),
            "https://cognitiveservices.azure.com/.default",
        )
        return AzureOpenAI(
            azure_endpoint=endpoint,
            api_version=api_version,
            azure_ad_token_provider=token_provider,
        )

    return AzureOpenAI(
        azure_endpoint=endpoint,
        api_version=api_version,
        api_key=os.environ["AZURE_OPENAI_API_KEY"],
    )


# --------------------------------------------------------------------------- #
# Tool implementations (called locally when the model requests them)
# --------------------------------------------------------------------------- #
def _tool_annotate(chrom: str, pos: int, ref: str, alt: str) -> dict[str, Any]:
    variant = annotate_mod.Variant(chrom=chrom, pos=int(pos), ref=ref, alt=alt)
    return annotate_mod.annotate_variant(variant)


def _tool_classify(annotation: dict[str, Any]) -> dict[str, Any]:
    return acmg.evaluate(annotation).to_dict()


TOOLS = [
    {
        "type": "function",
        "function": {
            "name": "annotate_variant",
            "description": (
                "Annotate a single genomic variant against MyVariant.info "
                "(ClinVar significance, gnomAD allele frequency, dbNSFP scores) "
                "and Ensembl VEP (most-severe consequence)."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "chrom": {"type": "string", "description": "Chromosome, e.g. 17 or chr17"},
                    "pos": {"type": "integer", "description": "1-based genomic position"},
                    "ref": {"type": "string", "description": "Reference allele"},
                    "alt": {"type": "string", "description": "Alternate allele"},
                },
                "required": ["chrom", "pos", "ref", "alt"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "classify_variant",
            "description": (
                "Run the simplified ACMG/AMP rule engine on an annotation dict "
                "previously returned by annotate_variant. Returns fired criteria "
                "and a classification."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "annotation": {
                        "type": "object",
                        "description": "The dict returned by annotate_variant.",
                    }
                },
                "required": ["annotation"],
            },
        },
    },
]

TOOL_IMPLS = {
    "annotate_variant": lambda args: _tool_annotate(**args),
    "classify_variant": lambda args: _tool_classify(args["annotation"]),
}


# --------------------------------------------------------------------------- #
# Agent loop
# --------------------------------------------------------------------------- #
def interpret_variant(client, deployment: str, variant: annotate_mod.Variant) -> str:
    """Run the tool-calling loop for one variant and return the memo markdown."""
    user_msg = (
        "Interpret this variant and write the memo.\n"
        f"chrom={variant.chrom} pos={variant.pos} ref={variant.ref} "
        f"alt={variant.alt} (id={variant.rsid}).\n"
        f"End the memo with EXACTLY this disclaimer line:\n{DISCLAIMER}"
    )
    messages: list[dict[str, Any]] = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": user_msg},
    ]

    # Bounded loop: the model may call annotate, then classify, then answer.
    for _ in range(6):
        resp = client.chat.completions.create(
            model=deployment,
            messages=messages,
            tools=TOOLS,
            tool_choice="auto",
            temperature=0.2,
        )
        msg = resp.choices[0].message
        messages.append(msg.model_dump(exclude_none=True))

        if not msg.tool_calls:
            content = msg.content or ""
            # Defensive: guarantee the disclaimer is present.
            if "NOT FOR CLINICAL USE" not in content.upper():
                content = content.rstrip() + "\n\n" + DISCLAIMER
            return content

        for call in msg.tool_calls:
            name = call.function.name
            try:
                args = json.loads(call.function.arguments or "{}")
                result = TOOL_IMPLS[name](args)
            except Exception as exc:  # surface tool errors back to the model
                result = {"error": f"{type(exc).__name__}: {exc}"}
            messages.append(
                {
                    "role": "tool",
                    "tool_call_id": call.id,
                    "name": name,
                    "content": json.dumps(result, default=str),
                }
            )

    return "Agent did not converge within the tool-call budget.\n\n" + DISCLAIMER


def _slug(variant: annotate_mod.Variant) -> str:
    return f"{variant.chrom}_{variant.pos}_{variant.ref}_{variant.alt}".replace(
        "chr", ""
    )


def _main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("vcf", help="path to a VCF file")
    ap.add_argument(
        "--out-dir", default="output/memos", help="directory for the .md memos"
    )
    ap.add_argument(
        "--limit", type=int, default=0, help="only process the first N variants"
    )
    args = ap.parse_args(argv)

    deployment = os.environ.get("AZURE_OPENAI_DEPLOYMENT", "gpt-4o")
    client = build_client()

    variants = annotate_mod.parse_vcf(args.vcf)
    if args.limit:
        variants = variants[: args.limit]

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    for v in variants:
        print(f"Interpreting {v.hgvs_id} ...", file=sys.stderr)
        memo = interpret_variant(client, deployment, v)
        path = out_dir / f"memo_{_slug(v)}.md"
        path.write_text(memo, encoding="utf-8")
        print(f"  -> {path}")

    return 0


if __name__ == "__main__":
    sys.exit(_main())
